[comments]
    enabled  = true
    provider = "giscus"

[comments.giscus]
    repo = "Xbox-Fan/my-blog"
    repoID = "R_kgDOTTWmHA"
    category = "Announcements"
    categoryID = "DIC_kwDOTTWmHM4DA4d2"
    mapping = "pathname"
    strict = false
    reactionsEnabled = true
    emitMetadata = false
    inputPosition = "bottom"
    lightTheme = "light"
    darkTheme = "dark"
    lang = "zh-cn"
    loading = "lazy"
