baseURL = 'https://ffmpig.pages.dev/'
locale = 'zh-CN'
title = 'FFmpig的个人网站'
theme = 'Stack'

[markup.goldmark.renderer]
    unsafe = true

[taxonomies]
    category = "categories"
    tag      = "tags"
